title = "Diante Cross"
baseURL = "https://diantecross.com/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "San Francisco Bay Area"
email = "dkrussellcross@gmail.com"
favicon = "/favicon.ico"
firstName = "Diante"
lastName = "Cross"
phone = "415-713-0800"
profileImage = "img/IMG_0366.JPG"
showQr = false
showContact = false
showBoards  = false
showCertifications = false
showSocializations = true
sections = ["skills","experience","education"]
vcardfields = [
    "name",
    "image",
    "org",
    "email",
    "workemail",
    "phone",
    "url",
    "title"
]

[params.google]

[params.google.analytics]
trackerID = ""

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/diantecross/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/diantekyrie/"

[params.customSections.resume]
    name = "Resume"
    url = "/resume"



[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"


[mediaTypes]
  [mediaTypes."text/vcard"]
    suffixes = ["vcf"]

[outputFormats]
  [outputFormats.VCard]
    mediaType = "text/vcard"
    baseName = "contact"
    isPlainText = true
    notAlternative = true